[package]
name = "rboson"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
byteorder = "1.5.0"

[lib]
name = "rboson"
path = "src/lib.rs"

[[bin]]
name = "rboson"
path = "src/main.rs"
